print(" SSS   L")
print("S   S  L")
print("S      L")
print(" SSS   L")
print("    S  L")
print("S   S  L")
print(" SSS   LLLLL")

print("BBBB   IIIII")
print("B   B    I")
print("B   B    I")
print("BBBB     I")
print("B   B    I")
print("B   B    I")
print("BBBB   IIIII")
